import React from "react";
import "../css/privacidadTerminos.css"

const Privacidad = () => {
    return (
        <div id="contenedorPrivacidad">
            <section>
                <div> <b>Política de privacidad</b></div>
                <br />
                <p>En cumplimiento a la Ley de Protección de Datos Personales N° 25.326 (la “Ley”), le informamos los términos y condiciones de la Política de Privacidad de DEGASA S.A. con domicilio en: Paroissien 1930, C.P. 1429, Ciudad Autónoma de Buenos Aires, Argentina (en adelante, “DEGASA").</p>
                <div><b>¿Qué información recopilamos?</b></div>
                <p>Los Datos Personales que el usuario libre y voluntariamente proporcione a DEGASA a través de este website (en adelante, el “Portal”) y/o a través de diversos medios, tales como restaurantes de DEGASA, vía telefónica, aplicaciones y/o encuestas. La información brindada por los usuarios de DEGASA podrá incluir (i) datos personales en general, incluyendo sin limitación nombre, apellido, edad o fecha de nacimiento, lugar de nacimiento, actividad, profesión, ocupación u oficio, domicilio particular, número telefónico, correo electrónico, entre otros; (ii) datos financieros sobre tarjetas bancarias; (iii) datos sobre preferencias en el consumo de los productos de DEGASA; y (iii) datos necesarios para cumplir con las obligaciones fiscales de DEGASA (en adelante los “Datos Personales”). DEGASA podrá utilizar diversos medios para identificar a los usuarios, pero no se responsabiliza por la certeza de los Datos Personales provistos por sus usuarios. Los usuarios garantizan y responden, en cualquier caso, por la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
                <div><b>¿Para qué utilizamos su información?</b></div>
                <p>Los Datos Personales que recopilamos los destinamos para: (i) fines de identificación y contacto, (ii) realizar las ventas de los productos que DEGASA comercializa, (iii) el envío y entrega de productos solicitados, (iv) fines de facturación, (v) registrarlo como cliente de DEGASA, (vi) para atender sus quejas, aclaraciones y sugerencias y en general para el cumplimiento de las obligaciones que puedan derivar de la relación comercial entre el usuario y DEGASA.
                    Adicionalmente, podremos utilizar los Datos Personales proporcionados para finalidades distintas (secundarias) como: (i) brindar al usuario información de nuestros productos y servicios, (ii) conocer su historial y preferencias de consumo de nuestros productos y servicios, (iii) mejorar nuestra atención en el servicio y la calidad de nuestros productos, (iv) para promover nuestros productos y servicios, (v) ofrecer productos, servicios, promociones y descuentos y, (vi) ofrecer al usuario participar en eventos, sorteos y trivias organizadas por DEGASA y sus proveedores seleccionados; y respecto de las cuales El usuario podrá limitar el uso o divulgación de los Datos Personales que proporcione a DEGASA en los términos señalados más adelante en la presente Política de Privacidad.
                    Se deja expresamente establecido que DEGASA se encuentra en cumplimiento de todos los principios que marca la Ley: licitud, calidad, consentimiento, información, finalidad, lealtad, proporcionalidad y responsabilidad.
                    Para el caso de que el usuario desee que su información no sea utilizada para las finalidades secundarias enumeradas precedentemente, agradeceremos que nos envíe un correo electrónico a la siguiente dirección: redsocial@kfc.com.ar, informando a DEGASA su oposición al uso de sus Datos Personales, sin que por ello se entienda ninguna negativa de servicio por parte de DEGASA.
                    De acuerdo al artículo 7 de la Ley, DEGASA en ningún caso procederá al registro de los llamados datos sensibles de los usuarios del Portal. En concordancia con la normativa vigente, se entenderán por datos sensibles los referentes a pertenencias raciales o étnicas, preferencias políticas, estado individual de salud, convicciones religiosas, filosóficas o morales; intimidad sexual y, en general, los que fomenten prejuicios y discriminaciones, o afecten la dignidad, la privacidad, la intimidad doméstica y la imagen privada de personas o familias.
                    DEGASA podrá obtener información anónima acerca de las visitas al Portal. Se considera información anónima toda aquella que no pueda ser asociada a un usuario concreto e identificado, como por ejemplo la fecha y hora de acceso al Portal, las secciones consultadas, etc.</p>
                <div><b>¿Con quién compartimos su información?</b></div>
                <p>DEGASA podrá contratar a terceros como proveedores de servicios seleccionados para administrar tanto este Portal como los Datos Personales que DEGASA recaba a través de éste, o por cualquier otro medio distinto, por lo que podría incluso remitirlos a dicho(s) proveedor(es), sin un fin comercial, sino únicamente para cumplir con la prestación de los servicios contratados, llevar a cabo encuestas para estudios de mercado, entrega de promociones, cupones, así como para fines de verificar y actualizar la información que el usuario proporcione. De igual manera DEGASA podrá compartir o remitir los Datos Personales a sus subsidiarias, filiales y demás empresas relacionadas, dentro y fuera del país para fines de identificar, analizar y realizar actividades de promoción y de comercialización de sus productos y servicios. DEGASA podrá revelar o permitir el acceso a sus Datos Personales para cumplir con la legislación aplicable o por requerimiento de la autoridad competente. En términos de la presente Política, podríamos transferir sus Datos Personales tanto dentro como fuera del país sin un fin comercial ni ilícito sino únicamente para promover y comercializar nuestros productos y servicios, así como aquellos de nuestros proveedores seleccionados, Se entiende que ha otorgado su consentimiento a la transferencia de sus Datos Personales si no manifiesta oposición a que los mismos sean transferidos.
                    Al proporcionar sus Datos Personales, el usuario confirma y acepta que ha leído y acepta la presente Política de Privacidad y las Condiciones Generales de uso de Contenidos, Información, Servicios y Tecnología que se encuentran disponibles en el sitio web www.kfc.com.ar, y otorga su consentimiento a lo estipulado en el presente por lo que manifiesta su consentimiento expreso a que sus Datos Personales sean tratados de acuerdo al presente.
                    DEGASA en ningún caso comercializará, venderá o rentará información personal sobre el usuario a un tercero sin un consentimiento previo.
                    Los Datos Personales proporcionados podrán compilarse y almacenarse en una o más bases de datos para el cumplimiento de las finalidades detalladas en el presente. Se hace la advertencia que DEGASA podrá utilizar "cookies" para confirmar la identificación del usuario, personalizar el acceso a este Portal y revisar su uso, con el solo propósito de mejorar su navegación y sus condiciones de funcionalidad, toda vez que mediante las citadas “cookies” no se recaban Datos Personales de los usuarios en términos de la Ley.
                    Para el caso de pedidos a través de nuestra aplicación o página de internet, DEGASA cuenta con los servicios de un tercero administrador, con quien se ha firmado un contrato a los efectos garantizar la confidencialidad de los Datos Personales a los que el mismo tenga acceso, quien recopilará los datos de los usuarios por nombre y cuenta en DEGASA dando cumplimiento con los términos y condiciones establecidos en el presente, y en todo momento será el responsable del tratamiento que se dé a los mismos.</p>
                <div><b>¿Qué medidas de seguridad y control utilizamos para la protección de sus Datos Personales?</b></div>
                <p>DEGASA tiene implementadas medidas de seguridad administrativas, técnicas y físicas para proteger sus Datos Personales contra daño, alteración, pérdida, destrucción o uso indebido, mismas que igualmente exigimos sean cumplidas por los proveedores de servicios, así como por nuestras subsidiarias, afiliadas y empresas relacionadas.</p>
                <div><b>¿Cuál es el área de DEGASA responsable del manejo y administración de los datos personales?</b></div>
                <p>El área responsable del manejo y la administración de los Datos Personales de este Portal es: el departamento de sistemas, cuya dirección de correo electrónico es redsocial@kfc.com.ar.</p>
                <div><b>¿Cómo puede usted limitar el uso y divulgación de sus Datos Personales, ejercer sus derechos ARCO y revocar su consentimiento al tratamiento?</b></div>
                <p>De conformidad con lo previsto por la Ley, uel usuario podrá limitar el uso o divulgación de los Datos Personales, así como ejercer los derechos de acceso, cancelación, rectificación y oposición al tratamiento de sus Datos Personales (en adelante, los derechos “ARCO”) o bien, revocar el consentimiento que haya otorgado a DEGASA para el tratamiento de sus Datos Personales, enviando directamente su solicitud al Comité de Datos Personales a través de la cuenta de correo electrónico antes mencionada. La solicitud para el ejercicio de los derechos ARCO deberá contener por lo menos: (a) nombre y domicilio u otro medio para comunicarle la respuesta a su solicitud; (b) los documentos que acrediten la identidad o, en su caso, la representación legal; (c) la descripción clara y precisa de los Datos Personales respecto de los que se solicita ejercer alguno de los derechos ARCO; y (d) cualquier otro elemento que facilite la localización de los Datos Personales.
                    En caso de que alguno de los Datos Personales del Titular sea inexacto o incompleto, el Titular además de indicar lo señalado anteriormente deberá señalar las modificaciones a realizarse y aportar la documentación necesaria que sustente su petición.
                    DEGASA se reserva el derecho a no cancelar los registros de los mencionados datos en los casos específicamente señalados por la Ley.
                    DEGASA tendrá un plazo máximo de 10 días corridos para informar sobre la procedencia de la solicitud de acceso, ratificación, cancelación u oposición. Tratándose de solicitudes de acceso a Datos Personales, procederá la entrega previa acreditación de la identidad del solicitante.
                    La Dirección Nacional de Protección de Datos Personales, órgano de control de la Ley, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de Datos Personales.</p>
                <div><b>¿Cuándo puede usted ejercer sus derechos ARCO?</b></div>
                <p>Podrá ejercer los derechos ARCO en cualquier momento, en intervalos no inferiores a seis (6) meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley, o bien, revocar el consentimiento que ha otorgado a DEGASA, para el tratamiento de los Datos Personales, enviando directamente tu solicitud al área responsable al correo electrónico previamente señalado en cualquier momento.</p>
                <div><b>Modificaciones a la Política de Privacidad.</b></div>
                <p>Nos reservamos el derecho de cambiar esta Política de Privacidad en cualquier momento y sin previo aviso. Cualquier modificación que se introduzca estará vigente a partir de su publicación en el Portal y el uso del Portal con posterioridad a la modificación de de la presente Política de Privacidad implica aceptación de dichos cambios por parte del usuario. Por su seguridad, consulte en todo momento que así lo desee el contenido de esta Política de Privacidad en nuestro Portal redsocial@kfc.com.ar</p>
                <div><b>Otras normatividades aplicables.</b></div>
                <p>DEGASA se encuentra ubicado en Argentina y todos los asuntos en relación a este Portal son regidos por las leyes de Argentina. Si el usuario se encuentra ubicado en algún otro país distinto de Argentina y nos contacta, por favor tome en cuenta que para el tratamiento de los Datos Personales que nos proporcione, su acuerdo y consentimiento se obtienen de conformidad con la Ley vigente en Argentina por lo tanto al momento de ingresar su información personal Usted autoriza y acepta su tratamiento en los términos de la presente Política de Privacidad.</p>
                <div><b>Consentimiento.</b></div>
                <p>El Titular consiente, en proporcionar los Datos Personales en la forma y para los fines señalados en la presente que los mismos sean transmitidos única y exclusivamente para los efectos señalados en el presente documento. En términos de la legislación vigente, se entenderá que el titular consiente tácitamente el tratamiento de sus datos, cuando puesto a su disposición la presente Política de Privacidad no manifieste su oposición.</p>
                <br />
                <p>Fecha de última actualización de esta Políticade Privacidad: 28/12/2018
                </p>
                <br />
                <ul>
                    <li>Facturación electrónica</li>
                    <li>Aviso de privacidad</li>
                    <li>DEGASA ARGENTINA</li>
                    <li>Bolsa de Trabajo</li>
                </ul>
            </section>
        </div>
    )
}

export default Privacidad